language: node_js
node_js:
  - '0.10'
before_install:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
before_script:
  - 'gem update --system'
  - 'gem install sass --version "=3.2.12"'
  - 'gem install compass --version "=0.12.2"'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
